src/Moryx.Identity.AccessManagement/Controllers/API/EntraIdAuthController.cs
// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Abstractions;
using Moryx.Identity.AccessManagement.Data;
using Moryx.Identity.Models;

namespace Moryx.Identity.AccessManagement.Controllers;

/// <summary>
/// API controller to provide actions regarding the single sign-on via Entra ID (Azure AD) in addition to the authentication controller.
/// </summary>
[Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]
[Route("api/auth")]
[ApiController]
public class EntraIdAuthController : ControllerBase
{
    private readonly MoryxUserManager _userManager;
    private readonly ITokenService _tokenService;
    private readonly IDownstreamApi _downstreamWebApi;

    /// <summary>
    /// Creates a new instance  of the <see cref="EntraIdAuthController"/>.
    /// </summary>
    /// <param name="userManager">The <see cref="MoryxUserManager"/> for MORYX users</param>
    /// <param name="tokenService">A token service for handling the JWTs</param>
    /// <param name="downstreamWebApi">The downstream API to call for the user data.</param>
    public EntraIdAuthController(
        MoryxUserManager userManager,
        ITokenService tokenService,
        IDownstreamApi downstreamWebApi)
    {
        _userManager = userManager;
        _tokenService = tokenService;
        _downstreamWebApi = downstreamWebApi;
    }

    /// <summary>
    /// Signs in via Microsoft Entra ID.
    /// The actual login via Entra ID is done through the middleware.
    /// This endpoint then provides its own session, just like the login via username and password.
    /// From that point on, the AccessManagement takes care of the accesses
    /// </summary>
    /// <returns>Redirects to the provided url.</returns>
    [Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]
    [HttpGet("signIn/microsoft")]
    public async Task<IActionResult> SignInViaMicrosoft([FromQuery] string redirectUrl)
    {
        // try to get the username
        if (User.Identity?.Name == null || User.Identity.Name.Contains('@') == false)
        {
            return BadRequest(new AuthResult
            {
                Errors = ["Failed to identify the user."],
                Success = false
            });
        }

        var userName = User.Identity.Name.Split('@')[0];

        var user = await _userManager.FindByNameAsync(userName);

        if (user == null)
        {
            user = new MoryxUser
            {
                UserName = userName
            };
            var userCreateResult = await _userManager.CreateAsync(user);
            if (userCreateResult.Succeeded == false)
            {
                return StatusCode(500, new AuthResult
                {
                    Errors = ["Failed to create the user."],
                    Success = false
                });
            }
        }

        try
        {
            await UpdateUserByEntraIdInformationAsync(user);
        }
        catch
        {
            return StatusCode(500, new AuthResult
            {
                Errors = ["Failed to access the remote user data."],
                Success = false
            });
        }

        await _userManager.UpdateAsync(user);
        // Refetch the user from db to avoid concurrency exception while generating a token
        user = await _userManager.FindByIdAsync(user.Id);
        var jwtToken = await _tokenService.GenerateTokenAsync(user);
        HttpContext.Response.Cookies.SetJwtCookie(jwtToken, user);

        return Redirect(redirectUrl);
    }

    private async Task UpdateUserByEntraIdInformationAsync(MoryxUser user)
    {

        // get user information from microsoft graph API
        using var response = await _downstreamWebApi.CallApiForUserAsync("DownstreamApi");
        response.EnsureSuccessStatusCode();

        var rawUserInfo = await response.Content.ReadFromJsonAsync<JsonDocument>();
        if (rawUserInfo.RootElement.TryGetProperty("givenName", out JsonElement givenName))
        {
            user.Firstname = givenName.GetString();
        }

        if (rawUserInfo.RootElement.TryGetProperty("surname", out JsonElement surname))
        {
            user.LastName = surname.GetString();
        }

        if (rawUserInfo.RootElement.TryGetProperty("mail", out JsonElement mail))
        {
            user.Email = mail.GetString();
            user.EmailConfirmed = true;
        }
        // there are also properties like businessPhones and officeLocation, but there is currently no reason to save them 
    }
}

src/Moryx.Identity.AccessManagement/Controllers/MVC/LoginController.cs
// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Moryx.Identity.AccessManagement.Models;

namespace Moryx.Identity.AccessManagement.Controllers;

public class LoginController : Controller
{
    private readonly MoryxUserManager _userManager;
    private readonly ITokenService _tokenService;
    private readonly IConfiguration _configuration;
    private readonly IPasswordResetService _pwResetService;

    public LoginController(MoryxUserManager userManager,
        ITokenService tokenService, IConfiguration configuration, IPasswordResetService passwordResetService)
    {
        _userManager = userManager;
        _tokenService = tokenService;
        _configuration = configuration;
        _pwResetService = passwordResetService;
    }

    public IActionResult Index()
    {
        if (Request.QueryString.HasValue)
        {
            ViewBag.ReturnUrl = Request.Query["returnUrl"].FirstOrDefault();
            ViewBag.ErrorMessage = Request.Query["viewBagError"].FirstOrDefault();
        }
        ViewBag.ShowLoginViaMicrosoft = _configuration.GetSection("EntraId").Exists();
        return View();
    }

    public async Task<IActionResult> Login(UserLoginModel userLoginModel, [FromQuery] string returnUrl)
    {

        var user = await _userManager.FindByNameAsync(userLoginModel.UserName);
        if (user is null)
            return ReturnIndexWithError(returnUrl);

        var passwordCorrect = await _userManager.CheckPasswordAsync(user, userLoginModel.Password);
        if (!passwordCorrect)
            return ReturnIndexWithError(returnUrl);

        var tokenResult = await _tokenService.GenerateTokenAsync(user);
        HttpContext.Response.Cookies.SetJwtCookie(tokenResult, user);

        if (!string.IsNullOrEmpty(returnUrl))
            return Redirect(Request.Query["returnUrl"]);

        if (await _userManager.IsInRoleAsync(user, Roles.SuperAdmin))
            return RedirectToAction("Index", "Users");
        return RedirectToAction("Index", "Home");
    }

    private IActionResult ReturnIndexWithError(string returnUrl)
    {
        ViewBag.ErrorMessage = "UserName or Password incorrect!";

        if (returnUrl != null)
            return RedirectToAction("Index", "Login", new { returnUrl = returnUrl, viewBagError = ViewBag.ErrorMessage });

        return RedirectToAction("Index", "Login", new { viewBagError = ViewBag.ErrorMessage });
    }

    public IActionResult Register()
    {
        return View();
    }

    public async Task<IActionResult> RegisterExecute(MoryxUserRegisterModel userModel)
    {
        var user = ModelConverter.GetUserFromUserRegisterModel(userModel);;

        var userCreateResult = await _userManager.CreateAsync(user, userModel.Password);
        if (userCreateResult.Succeeded)
            return RedirectToAction("Index", "Home");

        ViewBag.ErrorMessage = userCreateResult.Errors.First().Description;
        return View("Register");
    }

    public IActionResult Logout()
    {
        var token = Request.Cookies[MoryxIdentityDefaults.JWT_COOKIE_NAME];
        _tokenService.InvalidateRefreshTokenAsync(token).Wait();
        HttpContext.Response.Cookies.RemoveJwtCookie(_configuration["CookieDomain"]);
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> ResetView([FromQuery] string userName, [FromQuery] string resetToken, [FromQuery] string returnUrl = null)
    {
        var resetModel = new MoryxUserResetPasswordModel
        {
            ResetToken = resetToken ?? "",
            UserName = userName ?? ""
        };
        ViewBag.ReturnUrl = returnUrl;

        return View(model: resetModel);
    }

    public async Task<IActionResult> ResetPassword(MoryxUserResetPasswordModel resetModel)
    {
        var user = await _userManager.FindByNameAsync(resetModel.UserName);
        if (user == null)
        {
            ViewBag.ErrorMessage = "User not found";
            return View("ResetView", resetModel);
        }

        var pwReset = await _pwResetService.GetPasswordResetAsync(user.Id);
        if (pwReset == null || !pwReset.ResetToken.Equals(resetModel.ResetToken, StringComparison.OrdinalIgnoreCase))
        {
            ViewBag.ErrorMessage = "Invalid reset password token";
            return View("ResetView", resetModel);
        }
        else if (pwReset.ExpiryTime < DateTime.UtcNow)
        {
            ViewBag.ErrorMessage = "The reset password token has expired";
            return View("ResetView", resetModel);
        }

        await _userManager.RemovePasswordAsync(user);

        var addPasswordResult = await _userManager.AddPasswordAsync(user, resetModel.NewPassword);
        if (!addPasswordResult.Succeeded)
        {
            ViewBag.ErrorMessage = addPasswordResult.Errors.First().Description;
            return View("ResetView", resetModel);
        }
        await _pwResetService.RemovePasswordResetAsync(pwReset);
        await _userManager.UpdateAsync(user);

        var returnUrl = Request?.Query["returnUrl"].FirstOrDefault();

        return RedirectToAction("Index", new { returnUrl = returnUrl });
    }
}

src/Moryx.Identity.AccessManagement/Views/Login/Index.cshtml
@model Moryx.Identity.AccessManagement.Models.UserLoginModel
@{
    ViewData["Title"] = "Login";
}
    
<div class="tw-flex tw-justify-center">
    <div class="tw-w-full md:tw-w-1/2 lg:tw-w-1/3">
        <form asp-action="Login" asp-route-returnUrl="@ViewBag.ReturnUrl" class="tw-bg-white tw-shadow-md tw-rounded tw-px-8 tw-pt-6 tw-pb-8 tw-mb-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="tw-mb-4">
            <label asp-for="UserName" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2">User</label>
            <div class="tw-relative">
                <input asp-for="UserName" class="form-control" required/>
                <span class="tw-absolute tw-left-0 tw-top-0 tw-p-3">
                        <span class="material-symbols-outlined">person</span>
                </span>
            </div>
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
        <div class="tw-mb-4">
            <label asp-for="Password" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
            <div class="tw-relative">
                <input asp-for="Password" type="password" class="form-control" placeholder="**********" required/>
                <span class="tw-absolute tw-left-0 tw-top-0 tw-p-3">
                    <span class="material-symbols-outlined">lock</span>
                </span>
            </div>
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <div class="tw-mb-4">
            <input type="submit" value="Login" class="btn-primary tw-w-full" />
        </div>
        <div class="tw-mb-4">
            <a asp-controller="Login" asp-action="ResetView" asp-route-returnUrl="@ViewBag.ReturnUrl">Forgot Password?</a>
        </div>
        @if (ViewBag.ShowLoginViaMicrosoft)
        {
            <div class="tw-mb-4">
                <a class="btn-primary tw-block tw-text-center"
                   asp-controller="EntraIdAuth"
                   asp-action="SignInViaMicrosoft"
                   asp-all-route-data="@(new Dictionary<string, string> { { "redirectUrl", "/" } })">
                    Login with Microsoft
                </a>
            </div>
        }
    </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/Moryx.Identity.AccessManagement/Views/Login/Register.cshtml
@model Moryx.Identity.AccessManagement.Models.MoryxUserRegisterModel
@{
    ViewData["Title"] = "Register";
}

<div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-3">
    <div class="tw-col-span-1">
        <form asp-action="RegisterExecute">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="tw-mb-4">
                <label asp-for="UserName" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="Email" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="Password" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <input type="submit" value="Register" class="btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/Moryx.Identity.AccessManagement/Views/Login/ResetView.cshtml
@model Moryx.Identity.AccessManagement.Models.MoryxUserResetPasswordModel
@{
    ViewData["Title"] = "Reset Password";
}
<div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-3">
    <div class="tw-col-span-1">
        <form asp-action="ResetPassword" asp-route-returnUrl="@ViewBag.ReturnUrl">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="tw-mb-4">
                <label asp-for="UserName" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="UserName" type="text" value="@Model.UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="ResetToken" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="ResetToken" value="@Model.ResetToken" type="text" class="form-control" />
                <span asp-validation-for="ResetToken" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="NewPassword" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="NewPassword" type="password" class="form-control" />
                <span asp-validation-for="NewPassword" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="ConfirmNewPassword" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="ConfirmNewPassword" type="password" class="form-control" />
                <span asp-validation-for="ConfirmNewPassword" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <input type="submit" value="Save" class="btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}