src/Moryx.Identity.AccessManagement/Controllers/MVC/UserRolesController.cs
// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Moryx.Identity.AccessManagement.Data;
using Moryx.Identity.AccessManagement.Models;

namespace Moryx.Identity.AccessManagement.Controllers;

[Authorize(Roles = Roles.SuperAdmin)]
public class UserRolesController : Controller
{
    private readonly SignInManager<MoryxUser> _signInManager;
    private readonly MoryxUserManager _userManager;
    private readonly MoryxRoleManager _roleManager;

    public UserRolesController(MoryxUserManager userManager, SignInManager<MoryxUser> signInManager, MoryxRoleManager roleManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _roleManager = roleManager;
    }

    public async Task<IActionResult> Index(string userId)
    {
        var viewModel = new List<UserRolesViewModel>();
        var user = await _userManager.FindByIdAsync(userId);
        foreach (var role in _roleManager.Roles.ToList())
        {
            var userRolesViewModel = new UserRolesViewModel
            {
                RoleName = role.Name
            };
            if (await _userManager.IsInRoleAsync(user, role.Name))
            {
                userRolesViewModel.Selected = true;
            }
            else
            {
                userRolesViewModel.Selected = false;
            }
            viewModel.Add(userRolesViewModel);
        }
        var model = new ManageUserRolesViewModel
        {
            UserId = userId,
            UserName = user.UserName,
            UserRoles = viewModel
        };

        return View(model);
    }

    public async Task<IActionResult> Update(string id, ManageUserRolesViewModel model)
    {
        try
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);

            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            result = await _userManager.AddToRolesAsync(user, model.UserRoles.Where(x => x.Selected).Select(y => y.RoleName));

            var currentUser = await _userManager.GetUserAsync(User);
            await _signInManager.RefreshSignInAsync(currentUser);

            TempData["SuccessMessage"] = "Role has been updated successfully!";
        }
        catch
        {
            TempData["ErrorMessage"] = "Updating the role failed with an unexpected error!";
        }

        return RedirectToAction("Index", new { userId = id });
    }
}

src/Moryx.Identity.AccessManagement/Controllers/MVC/UsersController.cs
// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Moryx.Identity.AccessManagement.Models;

namespace Moryx.Identity.AccessManagement.Controllers;

[Authorize(Roles = Roles.SuperAdmin)]
public class UsersController : Controller
{
    private readonly MoryxUserManager _userManager;
    private readonly IConfiguration _configuration;
    private readonly IPasswordResetService _pwResetService;

    public UsersController(MoryxUserManager userManager, IConfiguration configuration, IPasswordResetService passwordResetService)
    {
        _userManager = userManager;
        _configuration = configuration;
        _pwResetService = passwordResetService;
    }

    public async Task<IActionResult> Index()
    {
        var users = await _userManager.Users.ToListAsync();
        return View(users);
    }

    public async Task<IActionResult> Edit(string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);
        var userModel = ModelConverter.GetUserUpdateModelFromUser(user);
        var pwReset = await _pwResetService.GetPasswordResetAsync(userId);
        if (pwReset != null)
            userModel.PasswordResetToken = pwReset.ResetToken;
        return View(userModel);
    }

    public async Task<IActionResult> GenerateResetToken(MoryxUserUpdateModel model)
    {
        var user = await _userManager.FindByNameAsync(model.UserName);
        if (user == null)
            return NotFound(model.UserName);

        var oldPwReset = await _pwResetService.GetPasswordResetAsync(user.Id);
        if (oldPwReset != null)
            await _pwResetService.RemovePasswordResetAsync(oldPwReset);

        await _pwResetService.GeneratePasswordResetAsync(user.Id);
        return RedirectToAction("Edit", new { userId = user.Id });

    }
    public async Task<IActionResult> Update(MoryxUserUpdateModel model)
    {
        var user = await _userManager.FindByNameAsync(model.UserName);
        if (user == null)
            return NotFound(model.UserName);

        user.Email = model.Email;
        user.Firstname = model.FirstName;
        user.LastName = model.LastName;

        await _userManager.UpdateAsync(user);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);
        if (user == null)
            return NotFound(userId);

        if (User.Identity.Name != user.UserName)
        {
            var result = await _userManager.DeleteAsync(user);
        }
        else
        {
            return BadRequest("You can not delete yourself.");
        }

        return RedirectToAction("Index");
    }
}

src/Moryx.Identity.AccessManagement/Views/Users/Edit.cshtml
@model Moryx.Identity.AccessManagement.Models.MoryxUserUpdateModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit @Model.UserName</h2>
<br />
<div class="tw-grid tw-grid-cols-1 md:tw-grid-cols-3">
    <div class="tw-col-span-1">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="tw-mb-4">
                <input asp-for="UserName" type="hidden" />
                <label asp-for="Email" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="FirstName" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="LastName" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <label asp-for="PasswordResetToken" class="tw-block tw-text-gray-700 tw-text-sm tw-font-bold tw-mb-2"></label>
                <div class="input-group tw-relative">
                    <input asp-for="PasswordResetToken" class="form-control" readonly />
                    <i id="togglePassword" class="fa fa-eye tw-absolute tw-right-24 tw-top-3 tw-cursor-pointer"></i>
                    <button class="btn-primary tw-bg-success-700 hover:tw-bg-success-800" asp-controller="Users" asp-action="GenerateResetToken">
                        Generate
                    </button>
                </div>
                <span asp-validation-for="PasswordResetToken" class="text-danger"></span>
            </div>
            <div class="tw-mb-4">
                <input type="submit" value="Save" class="btn-primary" />
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    var togglePassword = document.querySelector('#togglePassword');
    var password = document.querySelector('#PasswordResetToken');
    password.setAttribute('type', 'password');
    togglePassword.addEventListener('click', function (e) {
        const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
        password.setAttribute('type', type);
        this.classList.toggle('fa-eye-slash');
    });
</script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/Moryx.Identity.AccessManagement/Views/Users/Index.cshtml
@model IEnumerable<Moryx.Identity.AccessManagement.Data.MoryxUser>
@{
    ViewData["Title"] = "Users";
}

<table class="table table-striped table-bordered tw-mt-2" id="userTable">
    <thead>
        <tr>
            <th>User</th>
            <th>Email</th>
            <th class="tw-w-[10%]">
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>
                    <div class="tw-grid tw-grid-cols-1">
                        <div>
                            <a>
                                @user.UserName
                            </a>
                            <br>
                            <small>
                                @user.Firstname @user.LastName: @user.LastSignIn
                            </small>
                            <br>
                            <small>
                                @user.Id
                            </small>
                        </div>
                    </div>
                </td>
                <td>
                    <a>
                        @user.Email
                    </a>
                </td>
                <td>
                    <div class="dropdown">
                        <button type="button" class="btn-light dropdown-toggle" data-dropdown-toggle aria-haspopup="true" aria-expanded="false">
                            Action
                        </button>
                        <div class="dropdown-menu shadow">
                            <a style='margin-right:16px' asp-controller="Users" asp-action="Edit" asp-route-userId="@user.Id" class="dropdown-item">
                                <i class="fa fa-pencil"></i> Edit
                            </a>
                            <a style='margin-right: 16px' asp-controller="UserRoles" asp-action="Index" asp-route-userId="@user.Id" class="dropdown-item">
                                <i class="fa fa-wrench"></i> Manage Roles
                            </a>
                            @if (User.Identity.Name != user.UserName)
                            {
                                <a style='margin-right: 16px' asp-controller="Users" asp-action="Delete" asp-route-userId="@user.Id" class="dropdown-item">
                                    <i class="fa fa-trash"></i> Delete
                                </a>
                            }
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>