src/Moryx.Identity.AccessManagement/Controllers/MVC/RolePermissionsController.cs
// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Moryx.Identity.AccessManagement.Models;

namespace Moryx.Identity.AccessManagement.Controllers;

[Authorize(Roles = Roles.SuperAdmin)]
public class RolePermissionsController : Controller
{
    private readonly MoryxRoleManager _roleManager;
    private readonly IPermissionManager _permissionManager;

    public RolePermissionsController(MoryxRoleManager roleManager, IPermissionManager permissionManager)
    {
        _roleManager = roleManager;
        _permissionManager = permissionManager;
    }

    public async Task<ActionResult> Index(string roleId)
    {
        var model = new RolePermissionsViewModel();
        var allPermissions = _permissionManager.Permissions.Select(p => p.Name).ToList();

        var role = await _roleManager.FindByIdAsync(roleId);
        model.RoleId = roleId;
        model.RoleName = role.Name;

        var rolePermissions = await _permissionManager.FindForRoleAsync(role.Name);

        var rolePermissionValues = rolePermissions.Select(a => a.Name).ToList();
        var authorizedPermissions = allPermissions.Intersect(rolePermissionValues).ToList();

        model.Permissions = new List<PermissionViewModel>(allPermissions.Count);
        foreach (var permission in allPermissions)
        {
            var permissionViewModel = new PermissionViewModel { Value = permission };

            if (authorizedPermissions.Any(authorized => authorized == permission))
                permissionViewModel.Selected = true;

            model.Permissions.Add(permissionViewModel);
        }

        return View(model);
    }

    public async Task<IActionResult> Update(RolePermissionsViewModel model)
    {
        try
        {
            var permissions = await _permissionManager.FindForRoleAsync(model.RoleName);
            await _permissionManager.RemoveFromRoleAsync(model.RoleName, permissions);

            var selectedPermissions = model.Permissions.Where(a => a.Selected).Select(p => p.Value).ToList();

            await _permissionManager.AddToRoleAsync(model.RoleName, selectedPermissions);

            TempData["SuccessMessage"] = "Permissions has been updated successfully!";
        }
        catch
        {
            TempData["ErrorMessage"] = "Permission update was failed with an unexpected error!";
        }

        return RedirectToAction("Index", new { roleId = model.RoleId });
    }
}

src/Moryx.Identity.AccessManagement/Controllers/MVC/RolesController.cs
// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Moryx.Identity.AccessManagement.Data;

namespace Moryx.Identity.AccessManagement.Controllers;

[Authorize(Roles = Roles.SuperAdmin)]
public class RolesController : Controller
{
    private readonly MoryxRoleManager _roleManager;

    public RolesController(MoryxRoleManager roleManager)
    {
        _roleManager = roleManager;
    }

    public async Task<IActionResult> Index()
    {
        var roles = await _roleManager.Roles.ToListAsync();
        ViewBag.SuccessMessage = (string)TempData["SuccessMessage"];
        ViewBag.ErrorMessage = (string)TempData["ErrorMessage"];

        return View(roles);
    }

    [HttpPost]
    public async Task<IActionResult> AddRole(string roleName)
    {
        if (roleName != null)
        {
            if (await _roleManager.RoleExistsAsync(roleName))
            {
                TempData["ErrorMessage"] = $"A role '{roleName}' already exists";
            }
            else
            {
                await _roleManager.CreateAsync(new MoryxRole(roleName.Trim()));
                TempData["SuccessMessage"] = $"Successfully created role '{roleName}'";
            }
        }
        else
        {
            TempData["ErrorMessage"] = $"Please enter a role name";
        }
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Delete(string roleId)
    {
        var role = await _roleManager.FindByIdAsync(roleId);
        if (role == null)
        {
            TempData["ErrorMessage"] = $"Could not find a role with ID '{roleId}'";
        }
        else
        {
            await _roleManager.DeleteAsync(role);
            TempData["SuccessMessage"] = $"Successfully deleted role '{role.Name}'";
        }

        return RedirectToAction("Index");
    }
}

src/Moryx.Identity.AccessManagement/Views/Roles/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Roles";
}

<form method="post" asp-action="AddRole" asp-controller="Roles">
    <div class="input-group tw-max-w-md">
        <input name="roleName" class="form-control" placeholder="Role name" aria-label="Role name">
        <div class="input-group-append">
            <button class="btn-outline-info"><i class="fa fa-plus"></i> Add New Role</button>
        </div>
    </div>
</form>

<table class="table table-striped table-bordered tw-mt-2" id="roleTable">
    <thead>
        <tr>
            <th>Role</th>
            <th>Id</th>
            <th class="tw-w-[10%]">Actions</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var role in Model)
        {
            <tr>
                <td>@role.Name</td>
                <td>@role.Id</td>
                <td class="text-right">
                    @if (role.Name != Roles.SuperAdmin)
                    {
                        <div class="dropdown">
                            <button type="button" class="btn-light dropdown-toggle" data-dropdown-toggle aria-haspopup="true" aria-expanded="false">
                                Action
                            </button>

                            <div class="dropdown-menu shadow">

                                <a class="dropdown-item" asp-controller="Roles" asp-action="Delete" asp-route-roleId="@role.Id"><i class="fa fa-trash"></i> Delete</a>

                                <a style='margin-right: 16px' asp-controller="RolePermissions" asp-action="Index" asp-route-roleId="@role.Id" class="dropdown-item">
                                    <i class="fa fa-wrench"></i> Manage Permissions
                                </a>
                            </div>
                        </div>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>